[project]
name = "adventofcode2023"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "utils",
]

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.2",
]

[tool.uv.sources]
utils = { path = "utils", editable = true }
